# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - envs:
      - runtime.env
    name: runtime
    namespace: replaced-by-kustomize

nameSuffix: -h100-gpt-oss-20b

patches:
  - path: patch-nodeselector.yaml
  - path: patch-resources.yaml

replacements:
  - source:
      fieldPath: data.APP_LABEL
      kind: ConfigMap
      name: runtime
    targets:
      - fieldPaths:
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
        select:
          kind: Deployment
      - fieldPaths:
          - spec.selector.app
        select:
          kind: Service
  - source:
      fieldPath: data.CONTAINER_IMAGE_URL
      kind: ConfigMap
      name: vllm
    targets:
      - fieldPaths:
          - spec.template.spec.containers.[name=inference-server].image
        select:
          kind: Deployment
  - source:
      fieldPath: data.INFERENCE_KUBERNETES_NAMESPACE
      kind: ConfigMap
      name: deployment
    targets:
      - fieldPaths:
          - metadata.namespace
        select:
          kind: ConfigMap
      - fieldPaths:
          - metadata.namespace
        select:
          kind: Deployment
      - fieldPaths:
          - metadata.namespace
        select:
          kind: Service
      - fieldPaths:
          - metadata.namespace
        select:
          kind: ServiceAccount
  - source:
      fieldPath: data.INFERENCE_KUBERNETES_SERVICE_ACCOUNT
      kind: ConfigMap
      name: deployment
    targets:
      - fieldPaths:
          - spec.template.spec.serviceAccountName
        select:
          kind: Deployment
      - fieldPaths:
          - metadata.name
        select:
          kind: ServiceAccount
  - source:
      fieldPath: data.MODEL_BUCKET_NAME
      kind: ConfigMap
      name: deployment
    targets:
      - fieldPaths:
          - spec.template.spec.volumes.[name=huggingface-hub-model-bucket].csi.volumeAttributes.bucketName
        options:
          delimiter: .
          index: 0
        select:
          kind: Deployment
  - source:
      fieldPath: data.MODEL_ID
      kind: ConfigMap
      name: runtime
    targets:
      - fieldPaths:
          - spec.template.spec.volumes.[name=huggingface-hub-model-bucket].csi.volumeAttributes.mountOptions
        options:
          delimiter: "only-dir:"
          index: 1
        select:
          kind: Deployment
      - fieldPaths:
          - spec.template.spec.containers.[name=fetch-safetensors].volumeMounts.[name=huggingface-hub-model-bucket].mountPath
          - spec.template.spec.containers.[name=inference-server].volumeMounts.[name=huggingface-hub-model-bucket].mountPath
        options:
          delimiter: /
          index: 2
        select:
          kind: Deployment
  - source:
      fieldPath: data.MODEL_NAME
      kind: ConfigMap
      name: runtime
    targets:
      - fieldPaths:
          - spec.template.metadata.labels.[ai.gke.io/model]
        select:
          kind: Deployment

resources:
  - ../base
