apiVersion: apps/v1
kind: Deployment
metadata:
  name: precise-prefix-cache-routing-gpu-vllm-decode
  namespace: replaced-by-kustomize
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/compute-class: gpu-rtx-pro-6000-96gb-x2
        cloud.google.com/gke-gpu-count: '1'
