apiVersion: apps/v1
kind: Deployment
metadata:
  name: precise-prefix-cache-routing-gpu-vllm-decode
  namespace: replaced-by-kustomize
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: modelserver
        resources:
          limits:
            cpu: '10'
            memory: 128G
            nvidia.com/gpu: 1
          requests:
            cpu: '10'
            memory: 128G
            nvidia.com/gpu: 1
