apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mlflow-tracking
  template:
    metadata:
      labels:
        app: mlflow-tracking
    spec:
      serviceAccountName: "${MLP_DB_USER_KSA}"
      initContainers:
        - name: alloydb-auth-proxy
          restartPolicy: Always
          image: gcr.io/alloydb-connectors/alloydb-auth-proxy:latest
          args:
            - "${MLP_DB_INSTANCE_URI}"
            - "--psc"
            - "--port=5432"
            - "--auto-iam-authn"
            - "--structured-logs"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
      containers:
        - name: mlflow
          image: "${MLP_MLFLOW_IMAGE}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2"
              memory: "10Gi"
            limits:
              cpu: "2"
              memory: "10Gi"
          env:
            - name: MLP_MLFLOW_DATABASE_URI
              value: "${MLP_MLFLOW_DATABASE_URI}"
            - name: MLP_MLFLOW_ARTIFACT_LOCATION
              value: "${MLP_MLFLOW_ARTIFACT_LOCATION}"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-svc
spec:
  selector:
    app: mlflow-tracking
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
