apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mlflow-tracking
  template:
    metadata:
      labels:
        app: mlflow-tracking
    spec:
      serviceAccountName: ${MLFLOW_KSA}
      containers:
        - name: alloydb-proxy
          image: gcr.io/alloydb-connectors/alloydb-auth-proxy:latest
          imagePullPolicy: Always
          args:
            - "${DB_INSTANCE_URI}"
            - "--auto-iam-authn"
            - "--psc"
            - "--port=5432"
            - "--structured-logs"
          ports:
            - containerPort: 5432
              name: alloydb
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
        - args:
            - --default-artifact-root=gs://${MLFLOW_ARTIFACT_LOCATION}
          env:
            - name: MLFLOW_TRACKING_URI
              value: "${MLFLOW_DATABASE_URI}"
          name: mlflow
          image: ${MLFLOW_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: mlflow-port
          resources:
            requests:
              cpu: "2"
              memory: "10Gi"
            limits:
              cpu: "2"
              memory: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-svc
spec:
  selector:
    app: mlflow-tracking
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
