apiVersion: apps/v1
kind: Deployment
metadata:
  name: fine-tuned-model-deployment
  namespace: ml-serve-fine-tuned-model
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fine-tuned-model
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/memory-limit: 10Gi
        gke-gcsfuse/memory-request: 4Gi
      labels:
        app: fine-tuned-model
    spec:
      containers:
      - args:
        - --model=$(MODEL_ID)
        - --tensor-parallel-size=1
        command:
        - python3
        - -m
        - vllm.entrypoints.api_server
        env:
        - name: MODEL_ID
          value: /data/models/<your_model_id> # Absolute path to the model
        image: us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20240220_0936_RC01
        imagePullPolicy: IfNotPresent
        name: inference-server
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 10Gi
            memory: 7Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            ephemeral-storage: 10Gi
            memory: 7Gi
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /data/models
          name: gcs-fuse
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
        cloud.google.com/gke-nodepool: gpu-l4x2-g2s24 # Any L4 node pool will work
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: ondemand
        operator: Exists
      - effect: NoSchedule
        key: nvidia/gpu
        operator: Exists
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: gcs-fuse
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: true
          volumeAttributes:
            bucketName: flipkart-fine-tuned-model # mount the gcs bucket
            mountOptions: "implicit-dirs"
            gcsfuseLoggingSeverity: warning
            fileCacheCapacity: 40Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fine-tuned-model-service
  namespace: ml-serve-fine-tuned-model  # replace with your namespace
spec:
  selector:
    app: fine-tuned-model
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000