apiVersion: batch/v1
kind: Job
metadata:
  name: model-eval
  namespace: _NAMESPACE_
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: model-eval-job
    spec:
      serviceAccountName: _KSA_
      containers:
      - name: job
        image: _IMAGE_URL_
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
        - -c
        - |
          ACTION=predict python batch_prediction.py
        env:
        - name: "ENDPOINT"
          value: "_ENDPOINT_"
        - name: "MODEL_PATH"
          value: "_MODEL_PATH_"
        - name: "DATASET_OUTPUT_PATH"
          value: "_DATASET_OUTPUT_PATH_"
        - name: "MLP_PREDICTION_BUCKET"
          value: "_MLP_PREDICTION_BUCKET_"
        - name: "PREDICTIONS_FILE"
          value: "_PREDICTION_FILE_"  
        resources:
          requests:
            cpu: "2"
            memory: "5Gi"
          limits:
            cpu: "2"
            memory: "5Gi"
      restartPolicy: Never
