apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-onboarding-job
spec:
  template:
    spec:
      serviceAccountName: alloydb-setup-ksa # Service account with necessary permissions
      containers:
      - name: catalog-onboarding
        image: gcr.io/gkebatchexpce3c8dcb/catalog-onboarding:latest # IMAGE_URL
        env:
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: alloydb-secrets
              key: project_id
        - name: REGION
          value: "us-central1"
        - name: CLUSTER_ID
          value: "my-cluster"
        - name: INSTANCE_ID
          value: "my-instance"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: alloydb-secrets
              key: password
      restartPolicy: Never
