apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 1 # Adjust the number of pods as needed
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: us-docker.pkg.dev/V_PROJECT_ID/rag-artifacts/backend-api:v0.1.0 # Replace with your backend image
        imagePullPolicy: Always
        ports:
        - containerPort: 8000 # Replace with your backend application's port
        env:
        - name: TEXT_EMBEDDING_ENDPOINT
          value: "http://multimodal-embedding-model-service:80/text_embeddings"
        - name: IMAGE_EMBEDDING_ENDPOINT
          value: "http://multimodal-embedding-model-service:80/image_uri"
        - name: MULTIMODAL_EMBEDDING_ENDPOINT
          value: "http://multimodal-embedding-model-service:80/multimodal_embeddings"            
        resources:
          requests:
            cpu: "512m" 
            memory: "512Mi" 
          limits:
            cpu: "1"
            memory: "1Gi" # You might need more memory for the backend

---
apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
spec:
  selector:
    app: python-backend
  ports:
  - protocol: TCP
    port: 8000 # Expose the backend on the same port as the container
    targetPort: 8000
  type: ClusterIP # Expose the service internally within the cluster