apiVersion: v1
kind: Pod
metadata:
  name: tpu-warmkeeper-v2
  namespace: rl-kr-single-grpo-single-host
spec:
  nodeSelector:
    cloud.google.com/compute-class: tpu-v6e-2x4
  tolerations:
    - key: "google.com/tpu"
      operator: "Exists"
    - key: "cloud.google.com/compute-class"
      operator: "Exists"
  containers:
    - name: warmkeeper
      image: alpine:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
