# job.yaml for running the VLLM client in GKE
apiVersion: batch/v1
kind: Job
metadata:
  name: rag-backend
spec:
  template:
    spec:
      serviceAccountName: rag-ksa # Service account with necessary permissions
      containers:
      - name: rag-backend
        image: gcr.io/gkebatchexpce3c8dcb/rag-backend:latest  # Replace with your image
        # You might need to add resource requests/limits here
      restartPolicy: Never  # or OnFailure if you want retries
