apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimized-baseline-tpu-v6-vllm-decode
  namespace: replaced-by-kustomize
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: modelserver
        resources:
          limits:
            google.com/tpu: 4
          requests:
            google.com/tpu: 4
