apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimized-baseline-tpu-v6-vllm-decode
  namespace: replaced-by-kustomize
spec:
  template:
    spec:
      nodeSelector:
        $patch: replace
        cloud.google.com/compute-class: tpu-v6e-2x2
