apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: model-download-configmap
    envs:
      - model-download.env
resources:
  - load-model-to-cloud-storage.yaml
  - service-account.yaml
secretGenerator:
  - name: hugging-face-token-secret
    envs:
      - hugging-face-token.env

replacements:
  - source:
      kind: ConfigMap
      name: model-download-configmap
      fieldPath: data.IRA_BUCKET_NAME
    targets:
      - select:
          kind: Job
          name: transfer-model-to-gcs
        fieldPaths:
          - spec.template.spec.volumes.[name=gcsfuse].csi.volumeAttributes.bucketName
        options:
          delimiter: .
          index: 0
