apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: model-download-configmap
    envs:
      - model-download.env
resources:
  - load-model-to-cloud-storage.yaml
  - service-account.yaml
secretGenerator:
  - name: hugging-face-token-secret
    envs:
      - hugging-face-token.env
