# Copyright 2025 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-model-to-gcs
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: transfer-model-to-gcs
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      serviceAccountName: ira-model-download-ksa
      containers:
        - name: transfer-model-to-gcs
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:518.0.0-slim
          command:
            - bash
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail

              if [ -z "${HUGGING_FACE_TOKEN:-}" ]; then
                echo "Error: HUGGING_FACE_TOKEN is not set."
                exit 1
              fi
              if [ -z "${MODEL_ID:-}" ]; then
                echo "Error: MODEL_ID is not set."
                exit 1
              fi
               if [ -z "${IRA_BUCKET_NAME:-}" ]; then
                echo "Error: IRA_BUCKET_NAME is not set."
                exit 1
              fi

              echo "Downloading ${MODEL_ID} to ${IRA_BUCKET_NAME} Cloud Storage bucket"
              echo "Debug Hugging Face token length: ${#HUGGING_FACE_TOKEN}"

              pip3 install -U "huggingface_hub[cli]==0.30.2" --break-system-packages

              huggingface-cli download --repo-type model ${MODEL_ID} --local-dir /local/temp --token ${HUGGING_FACE_TOKEN}

              rm -rfv /local/temp/.cache
              mkdir -pv "/local/${MODEL_ID}"
              mv -v /local/temp/* "/local/${MODEL_ID}/"
              rm -rfv /local/temp /local/.gcsfuse_tmp
          env:
            - name: MODEL_ID
              valueFrom:
                configMapKeyRef:
                  key: MODEL_ID
                  name: ira-model-configmap
            - name: IRA_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: IRA_BUCKET_NAME
                  name: ira-model-configmap
            - name: HUGGING_FACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hugging-face-token-secret
                  key: HUGGING_FACE_TOKEN
          # If you want to consume less resources, don't install the hf_net
          # package, at the expense of download speed.
          resources:
            limits:
              cpu: 2000m
              memory: 8Gi
            requests:
              cpu: 2000m
              memory: 8Gi
          volumeMounts:
            - name: gcsfuse
              mountPath: /local
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: gcsfuse
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: cloud-storage-bucket-name
      tolerations:
        - key: "on-demand"
          value: "true"
          operator: "Equal"
          effect: "NoSchedule"
