# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transfer-model-to-gcs
  namespace: replaced-by-kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: premium-rwo
---
apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-model-to-gcs
  namespace: replaced-by-kustomize
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/volumes: "true"
      labels:
        app: transfer-model-to-gcs
    spec:
      containers:
        - command:
            - bash
            - "-c"
            - |
              set -o errexit
              set -o nounset
              set -o pipefail

              if [ -z "${MODEL_ID:-}" ]; then
                echo "Error: MODEL_ID is not set."
                exit 1
              fi
               if [ -z "${MODEL_BUCKET_NAME:-}" ]; then
                echo "Error: MODEL_BUCKET_NAME is not set."
                exit 1
              fi

              echo "Downloading ${MODEL_ID} to ${MODEL_BUCKET_NAME} Cloud Storage bucket"
              echo "Debug Hugging Face token path: ${HF_TOKEN_PATH}"

              pip3 install --break-system-packages --upgrade huggingface_hub[cli] hf_transfer

              huggingface-cli download --repo-type model ${MODEL_ID} --local-dir /local/temp

              rm -rfv /local/temp/.cache
              mkdir -pv "/local/${MODEL_ID}"
              mv -v /local/temp/* "/local/${MODEL_ID}/"
              rm -rfv /local/temp /local/.gcsfuse_tmp
          env:
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "1"
            - name: MODEL_ID
              valueFrom:
                configMapKeyRef:
                  key: MODEL_ID
                  name: downloader
            - name: MODEL_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: MODEL_BUCKET_NAME
                  name: downloader
            - name: HF_TOKEN_PATH
              value: /var/run/secrets/huggingface.co/token
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:529.0.0-slim
          name: transfer-model-to-gcs
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 4000m
              memory: 8Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /local
              name: huggingface-hub-model-bucket
            - mountPath: /var/run/secrets/huggingface.co
              name: huggingface-token
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 10000
      serviceAccountName: replaced-by-kustomize
      terminationGracePeriodSeconds: 0
      volumes:
        - emptyDir:
            medium: Memory
          name: dev-shm
        - name: gke-gcsfuse-buffer
          persistentVolumeClaim:
            claimName: transfer-model-to-gcs
        - csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: replaced-by-kustomize
          name: huggingface-hub-model-bucket
        - csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: huggingface-token-read
          name: huggingface-token
  ttlSecondsAfterFinished: 600
