# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hf-model-to-gcs
  namespace: replaced-by-kustomize
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/volumes: "true"
      labels:
        app: hf-model-to-gcs
    spec:
      containers:
        - args: ["/scripts/run.sh"]
          command: ["/bin/sh", "-c"]
          env:
            - name: HF_TOKEN_PATH
              value: /var/run/secrets/huggingface.co/token
            - name: HF_MAX_WORKERS
              value: "8"
            - name: HF_XET_CACHE
              value: /local/hf/xet
            - name: HF_XET_NUM_CONCURRENT_RANGE_GETS
              value: "16"
            - name: HF_XET_HIGH_PERFORMANCE
              value: "1"
            - name: MODEL_ID
              valueFrom:
                configMapKeyRef:
                  key: MODEL_ID
                  name: download
            - name: MODEL_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: MODEL_BUCKET_NAME
                  name: download
            - name: REPLACE_EXISTING
              value: "true"
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
          name: hf-model-to-gcs
          resources:
            requests:
              cpu: 2000m
              ephemeral-storage: 1Gi
              memory: 10Gi
          volumeMounts:
            - mountPath: /gcs
              name: huggingface-hub-model-bucket
            - mountPath: /scripts
              name: scripts
            - mountPath: /var/run/secrets/huggingface.co
              name: huggingface-token
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 10000
      serviceAccountName: replaced-by-kustomize
      terminationGracePeriodSeconds: 0
      volumes:
        - configMap:
            defaultMode: 0744
            name: hf-model-to-gcs
          name: scripts
        - csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: replaced-by-kustomize
          name: huggingface-hub-model-bucket
        - csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: huggingface-token-read
          name: huggingface-token
