apiVersion: batch/v1
kind: Job
metadata:
  name: hf-model-to-gcs
  namespace: replaced-by-kustomize
spec:
  template:
    spec:
      containers:
        - name: hf-model-to-gcs
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-token
                  key: token
            - name: HF_TOKEN_PATH
              value: /tmp/token
          volumeMounts:
            - name: huggingface-token
              mountPath: /var/run/secrets/huggingface.co
              $patch: delete
      volumes:
        - name: huggingface-token
          $patch: delete
