apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: huggingface-token-read
  namespace: replaced-by-kustomize
spec:
  parameters:
    secrets: |
      - resourceName: "projects/accelerated-platforms-dev/secrets/acp-uc1-b-huggingface-hub-access-token-read/versions/latest"
        path: "token"
  provider: gke
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: huggingface-token-write
  namespace: replaced-by-kustomize
spec:
  parameters:
    secrets: |
      - resourceName: "projects/accelerated-platforms-dev/secrets/acp-uc1-b-huggingface-hub-access-token-write/versions/latest"
        path: "token"
  provider: gke
