apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: tpu-v6e-2x4
spec:
  activeMigration:
    optimizeRulePriority: true
  nodePoolAutoCreation:
    enabled: true
  priorities:
    # Use a specific reservation.
    # - machineType: ct6e-standard-8t
    #   maxPodsPerNode: 32
    #   reservations:
    #     affinity: Specific
    #     specific:
    #       - name: tpu-v6e-slice-specific
    #         reservationBlock:
    #           name: <RESERVATION_NAME>
    #   spot: false
    #   tpu:
    #     count: 8
    #     topology: 2x4
    #     type: tpu-v6e-slice

    # Use on-demand
    - machineType: ct6e-standard-8t
      maxPodsPerNode: 32
      spot: false
      tpu:
        count: 8
        topology: 2x4
        type: tpu-v6e-slice

    # Use DWS FlexStart with 7 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      machineType: ct6e-standard-8t
      maxPodsPerNode: 32
      maxRunDurationSeconds: 604800
      tpu:
        count: 8
        topology: 2x4
        type: tpu-v6e-slice

    # Use DWS FlexStart with 1 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      machineType: ct6e-standard-8t
      maxPodsPerNode: 32
      maxRunDurationSeconds: 86400
      tpu:
        count: 8
        topology: 2x4
        type: tpu-v6e-slice

    # Use spot
    - machineType: ct6e-standard-8t
      maxPodsPerNode: 32
      spot: true
      tpu:
        count: 8
        topology: 2x4
        type: tpu-v6e-slice
