apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-frontend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: rag-frontend
  template:
    metadata:
      labels:
        app: rag-frontend
    spec:
      containers:
      - name: rag-frontend
        image: us-docker.pkg.dev/V_PROJECT_ID/rag-artifacts/frontend-api:v0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7860 
        env:
        - name: BACKEND_SERVICE_ENDPOINT
          value: V_BACKEND_SERVICE_ENDPOINT
        resources:
          requests:
            cpu: "512m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "512Mi" 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-rag-svc
spec:
  selector:
    app: rag-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7860 
  type: ClusterIP