images:
  - ${_DESTINATION}
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
serviceAccount:
steps:
  - name: 'docker:28.0.4"'
    args:
      - build
      - -t
      - ${_DESTINATION}
      - .
