# Copyright 2025 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
kind: Service
metadata:
  name: vllm
spec:
  selector:
    app: vllm
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  selector:
    matchLabels:
      app: vllm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vllm
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
    spec:
      containers:
        # Load safetensors files in the gcsfuse cache
        - name: fetch-safetensors
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "########### $(date) - Starting parallel-fetch-safetensors for model: ${MODEL_ID}"
              ls -alR /gcs
              find /gcs/${MODEL_ID}/*safetensors -type f | xargs -I {} -P 15 sh -c 'echo "########### $(date) - Fetching: {}"; dd if={} of=/dev/null'
              echo "########### $(date) - Finished parallel-fetch-safetensors"
              sleep infinity
          env:
            - name: MODEL_ID
              valueFrom:
                configMapKeyRef:
                  key: MODEL_ID
                  name: ira-model-configmap
          volumeMounts:
            - name: gcsfuse
              mountPath: /gcs
              readOnly: true
        - name: inference-server
          args:
            - --disable-log-requests
            - --gpu-memory-utilization=0.95
            - --model=/gcs/$(MODEL_ID)
            - --tensor-parallel-size=$(TENSOR_PARALLEL_SIZE)
            - --trust-remote-code
            - --max-model-len=$(MAX_MODEL_LEN)
          env:
            - name: MAX_MODEL_LEN
              valueFrom:
                configMapKeyRef:
                  key: MAX_MODEL_LEN
                  name: ira-model-configmap
            - name: MODEL_ID
              valueFrom:
                configMapKeyRef:
                  key: MODEL_ID
                  name: ira-model-configmap
            - name: TENSOR_PARALLEL_SIZE
              valueFrom:
                configMapKeyRef:
                  key: TENSOR_PARALLEL_SIZE
                  name: ira-model-configmap
          image: vllm/vllm-openai:v0.8.4
          imagePullPolicy: Always
          readinessProbe:
            failureThreshold: 6000
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8000
              name: metrics
          resources: {}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: gcsfuse
              mountPath: /gcs
              readOnly: true
      serviceAccountName: ira-online-gpu-ksa
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "on-demand"
          value: "true"
          operator: "Equal"
          effect: "NoSchedule"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: gcsfuse
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: cloud-storage-bucket-name
              # Leave the only-dir option at the end of the mountOptions value
              # because Kustomize will take care of replacing it
              mountOptions: "metadata-cache:ttl-secs:-1,metadata-cache:stat-cache-max-size-mb:-1,metadata-cache:type-cache-max-size-mb:-1,metadata-cache:negative-ttl-secs:0,file-cache:max-size-mb:-1,file-cache:cache-file-for-range-read:true,file-cache:enable-parallel-downloads:true,implicit-dirs,file-system:kernel-list-cache-ttl-secs:-1,only-dir:MODEL_ID"
              skipCSIBucketAccessCheck: "true"
        - name: gke-gcsfuse-cache
          emptyDir:
            medium: Memory
        - name: gke-gcsfuse-tmp
          emptyDir:
            medium: Memory
        - name: gke-gcsfuse-buffer
          emptyDir:
            medium: Memory
