environment_name       = "ml-flow"
environment_project_id = "gkebatchenv3a4ec43f"
git_namespace          = "IshmeetMehta"
git_user_email         = "ishmeetmehta@gmail.com"
git_user_name          = "ishmeetmehta"
iap_domain             = "google.com"
