# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PodTemplate
metadata:
  name: a100-job
  namespace: ml-team
template:
  spec:
    nodeSelector:
      cloud.google.com/gke-nodepool: gpu-a100x2-a2h2-dws
    tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "on-demand"
      value: "true"
      operator: "Equal"
      effect: "NoSchedule"      
    containers:
    - name: pi
      image: perl
      command: ["/bin/sh"]
      resources:
        limits:
          cpu: "700m"
          nvidia.com/gpu: 2
        requests:
          cpu: "700m"
          nvidia.com/gpu: 2
    restartPolicy: Never
---
apiVersion: autoscaling.x-k8s.io/v1beta1
kind: ProvisioningRequest
metadata:
  name: a100-job
  namespace: ml-team
spec:
  provisioningClassName: queued-provisioning.gke.io
  parameters:
    maxRunDurationSeconds: "86400"
  podSets:
  - count: 1
    podTemplateRef:
      name: a100-job
