# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: rag-etl-data
spec:
  template:
    metadata:
      labels:
        app: rag-etl
    spec:
      restartPolicy: Never
      serviceAccountName: rag-ksa
      containers:
      - name: rag-etl
        image: python:3.11
        command: ["/bin/sh", "-c"]        
        args:
        - |
          cd /codes
          pip3 install -r requirements.in
          cd /tmp
          python3 /codes/populate_data.py
        env:
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: alloydb-config
              key: pghost
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: alloydb-config
              key: pgdatabase
        - name: DATA_URL
          value: "https://www.kaggle.com/api/v1/datasets/download/PromptCloudHQ/flipkart-products"
        - name: DATAFILE
          value: flipkart_com-ecommerce_sample.csv
        - name: TABLENAME
          value: test_flipkart_tmp
        - name: RECREATE
          value: "yes"
        - name: EMBEDDING_DESC
          value: "emb:uniq_id:description"
        volumeMounts:
        - name: codes
          mountPath: /codes
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: codes
        configMap:
          name: rag-etl
