apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-a100-40gb-x2
spec:
  activeMigration:
    optimizeRulePriority: true
  priorities:
  # Use reservations if available, fall back to on-demand otherwise
  - gpu:
      count: 2
      driverVersion: latest
      type: nvidia-tesla-a100
    machineType: a2-highgpu-2g
    maxPodsPerNode: 16
    reservations:
      affinity: AnyBestEffort
    spot: false

  # Use DWS FlexStart
  # - flexStart:
  #     enabled: true
  #     nodeRecycling:
  #       leadTimeSeconds: 3600
  #   gpu:
  #     count: 2
  #     driverVersion: latest
  #     type: nvidia-tesla-a100 
  #   machineType: a2-highgpu-2g
  #   maxPodsPerNode: 16

  # Use spot
  - gpu:
      count: 2
      driverVersion: latest
      type: nvidia-tesla-a100
    machineType: a2-highgpu-2g
    maxPodsPerNode: 16
    spot: true

  nodePoolAutoCreation:
    enabled: true
