apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-a100-40gb-x2
spec:
  activeMigration:
    optimizeRulePriority: true
  nodePoolAutoCreation:
    enabled: true
  priorities:
    # Use a specific reservation
    # - gpu:
    #     count: 2
    #     driverVersion: latest
    #     type: nvidia-tesla-a100
    #   machineType: a2-highgpu-2g
    #   maxPodsPerNode: 32
    #   reservations:
    #     affinity: Specific
    #     specific:
    #       - name: nvidia-tesla-a100-specific
    #         reservationBlock:
    #           name: <RESERVATION_NAME>
    #   spot: false

    # Use any reservation
    - gpu:
        count: 2
        driverVersion: latest
        type: nvidia-tesla-a100
      machineType: a2-highgpu-2g
      maxPodsPerNode: 32
      reservations:
        affinity: AnyBestEffort
      spot: false

    # Use on-demand
    - gpu:
        count: 2
        driverVersion: latest
        type: nvidia-tesla-a100
      machineType: a2-highgpu-2g
      maxPodsPerNode: 32
      spot: false

    # Use DWS FlexStart with 7 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      gpu:
        count: 2
        driverVersion: latest
        type: nvidia-tesla-a100
      machineType: a2-highgpu-2g
      maxPodsPerNode: 32
      maxRunDurationSeconds: 604800

    # Use DWS FlexStart with 1 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      gpu:
        count: 2
        driverVersion: latest
        type: nvidia-tesla-a100
      machineType: a2-highgpu-2g
      maxPodsPerNode: 32
      maxRunDurationSeconds: 86400

    # Use spot
    - gpu:
        count: 2
        driverVersion: latest
        type: nvidia-tesla-a100
      machineType: a2-highgpu-2g
      maxPodsPerNode: 32
      spot: true
