# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: multimodal-embedding-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multimodal-embedding-model
  template:
    metadata:
      labels:
        app: multimodal-embedding-model
    spec:
      serviceAccountName: V_KSA
      containers:
      - env:
        - name: "PORT"
          value: "5000"
        image: V_IMAGE
        imagePullPolicy: Always
        name: multimodal-embedding-model
        resources:
          limits:
            cpu: "2"
            memory: "25Gi"
            ephemeral-storage: "25Gi"
            nvidia.com/gpu: "2"
          requests:
            cpu: "2"
            memory: "25Gi"
            ephemeral-storage: "25Gi"
            nvidia.com/gpu: "2"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
      - key: "on-demand"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: multimodal-embedding-model
spec:
  selector:
    app: multimodal-embedding-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
