apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: vllm-openai
  namespace: ml-serve
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vllm-openai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vllm-openai
    spec:
      containers:
      - args:
        - --model=$(MODEL)
        - --tensor-parallel-size=2
        env:
        - name: MODEL
          value: /data/models/model-gemma2-a100/experiment-a2aa2c3it1
        - name: VLLM_ATTENTION_BACKEND
          value: FLASHINFER
        image: vllm/vllm-openai:v0.6.1.post2
        imagePullPolicy: IfNotPresent
        name: inference-server
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 25Gi
            memory: 25Gi
            nvidia.com/gpu: "2"
          requests:
            cpu: "2"
            ephemeral-storage: 25Gi
            memory: 25Gi
            nvidia.com/gpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /data/models
          name: model-disk
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
        pool-type: l4-2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: cloud.google.com/gke-queued
        operator: Equal
        value: "true"
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: model-disk
        persistentVolumeClaim:
          claimName: pvc-model-weights-claim-1024gb-zone-a-ro
          readOnly: true
