# Copyright 2024 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: batch/v1
kind: Deployment
metadata:
  name: benchmark
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: benchmark-job
    spec:
      containers:
      - args:
        - '-c'
        - |
          ACTION=benchmark python3 /locustfile.py
        command: ["/bin/sh"]
        env:
        - name: ENDPOINT
          value: _ENDPOINT_
        - name: MODEL_ID
          value: _BENCHMARK_MODEL_PATH_
        - name: HOST
          value: _HOST_
        image: _IMAGE_URL_
        imagePullPolicy: Always
        name: job
        resources:
          limits:
            cpu: '2'
            memory: 5Gi
          requests:
            cpu: '2'
            memory: 5Gi
      restartPolicy: Never
      serviceAccountName: _KSA_
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.gke.io/load-balancer-type: Internal
  labels:
    app: benchmark
  name: locust-web
spec:
  ports:
  - name: loc-master-web
    port: 8089
    protocol: TCP
    targetPort: loc-master-web
  selector:
    app: benchmark
  type: LoadBalancer