apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend-deployment
  namespace: ml-team
spec:
  replicas: 1 # Adjust replica count as needed
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
      - name: rag
        #image: us-docker.pkg.dev/gkebatchexpce3c8dcb/embedding-artifacts/blip2:v4.0 # Update the image location
        image: gcr.io/gkebatchexpce3c8dcb/rag-backend:latest
        resources:
          requests:
            cpu: "2"
            memory: "25Gi"
            ephemeral-storage: "25Gi"
          limits:
            cpu: "2"
            memory: "25Gi"
            ephemeral-storage: "25Gi"
      nodeSelector:
        resource-type: "cpu"
      tolerations:
      - key: "on-demand"
        value: "true"
        operator: "Equal"
        effect: "NoSchedule"
      serviceAccountName: rag-ksa
---

apiVersion: v1
kind: Service
metadata:
  name: rag-backend-service
spec:
  selector:
    app: rag
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
