apiVersion: apps/v1 
kind: Deployment
metadata:
  name: not-applicable
spec:
  template:
    nodeSelector:
      resource-type: system
    spec:
      tolerations:
      - effect: NoSchedule
        key: "components.gke.io/gke-managed-components"
        operator: "Equal"
        value: "true"
