apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-h200-141gb-x8-ultra
spec:
  activeMigration:
    optimizeRulePriority: true
  nodePoolAutoCreation:
    enabled: true
  priorities:
    # Use reservations if available, fall back to on-demand otherwise
    - gpu:
        count: 8
        driverVersion: latest
        type: nvidia-h200-141gb
      machineType: a3-ultragpu-8g
      maxPodsPerNode: 16
      reservations:
        affinity: AnyBestEffort
      spot: false

    # Use DWS FlexStart with 7 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      gpu:
        count: 8
        driverVersion: latest
        type: nvidia-h200-141gb
      machineType: a3-ultragpu-8g
      maxPodsPerNode: 16
      maxRunDurationSeconds: 604800

    # Use spot
    - gpu:
        count: 8
        driverVersion: latest
        type: nvidia-h200-141gb
      machineType: a3-ultragpu-8g
      maxPodsPerNode: 16
      spot: true
