platform_custom_role_unique_suffix = "1778090610"
platform_default_project_id        = "accelerated-platforms-dev"
platform_default_region            = "us-central1"
platform_name                      = "az-fast"
resource_name_prefix               = "inf"
