custom_metrics_adapter_version         = "0.16.2"
inference_gateway_kubernetes_namespace = "gke-gateway"
inference_gateway_version              = "1.1.0"
jobset_version                         = "0.10.1"
kuberay_version                        = "1.5.1"
kueue_version                          = "0.14.4"
lws_version                            = "0.7.0"
