apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: tpu-v5p-2x2x4
spec:
  activeMigration:
    optimizeRulePriority: true
  priorities:
  # TPU currently only supports Specific affinity.
  # - machineType: 
  #   maxPodsPerNode: 16
  #   reservations:
  #     affinity: AnyBestEffort
  #   spot: false
  #   tpu:
  #     count: 4
  #     topology: 2x2x4
  #     type: tpu-v5p-slice
  
  # Use on-demand
  - maxPodsPerNode: 16
    spot: false
    tpu:
      count: 4
      topology: 2x2x4
      type: tpu-v5p-slice
  
  # Use DWS FlexStart, currently not support for TPUs as of 4/18
  # - flexStart:
  #     enabled: true
  #     nodeRecycling:
  #       leadTimeSeconds: 3600
  #   maxPodsPerNode: 16
  #   tpu:
  #     count: 4
  #     topology: 2x2x4
  #     type: tpu-v5p-slice
  
  # Use spot
  - maxPodsPerNode: 16
    spot: true
    tpu:
      count: 4
      topology: 2x2x4
      type: tpu-v5p-slice

  nodePoolAutoCreation:
    enabled: true
