apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: tpu-v5p-2x2x1
spec:
  activeMigration:
    optimizeRulePriority: true
  nodePoolAutoCreation:
    enabled: true
  priorities:
    # Use a specific reservation
    # - maxPodsPerNode: 32
    #   reservations:
    #     affinity: Specific
    #     specific:
    #       - name: tpu-v5p-slice-specific
    #         reservationBlock:
    #           name: <RESERVATION_NAME>
    #   spot: false
    #   tpu:
    #     count: 4
    #     topology: 2x2x1
    #     type: tpu-v5p-slice

    # Use on-demand
    - maxPodsPerNode: 32
      spot: false
      tpu:
        count: 4
        topology: 2x2x1
        type: tpu-v5p-slice

    # Use DWS FlexStart with 7 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      maxPodsPerNode: 32
      maxRunDurationSeconds: 604800
      tpu:
        count: 4
        topology: 2x2x1
        type: tpu-v5p-slice

    # Use DWS FlexStart with 1 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      maxPodsPerNode: 32
      maxRunDurationSeconds: 86400
      tpu:
        count: 4
        topology: 2x2x1
        type: tpu-v5p-slice

    # Use spot
    - maxPodsPerNode: 32
      spot: true
      tpu:
        count: 4
        topology: 2x2x1
        type: tpu-v5p-slice
