# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-it-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-it-model
  template:
    metadata:
      labels:
        app: rag-it-model
        ml-platform: vllm-openai
      annotations:
    spec:
      containers:
      - name: inference-server
        args:
        - --model=$(MODEL)
        - --tensor-parallel-size=1
        env:
        - name: MODEL
          value: google/gemma-2-2b-it
        - name: VLLM_ATTENTION_BACKEND
          value: FLASHINFER
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        image: vllm/vllm-openai:v0.5.3.post1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "2"
            memory: "25Gi"
            ephemeral-storage: "25Gi"
            nvidia.com/gpu: "2"
          limits:
            cpu: "2"
            memory: "25Gi"
            ephemeral-storage: "25Gi"
            nvidia.com/gpu: "2"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
            medium: Memory
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
        cloud.google.com/gke-gpu-driver-version: latest
      tolerations:
      - effect: "NoSchedule"
        key: "nvidia/gpu"
        operator: "Equal"
        value: "present"
      - effect: "NoSchedule"
        key: "on-demand"
        operator: "Equal"
        value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: rag-it-model
spec:
  selector:
    app: rag-it-model
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
