apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-h100-80gb-x1-high
spec:
  activeMigration:
    optimizeRulePriority: true
  priorities:
    # Use reservations if available, fall back to on-demand otherwise
    - gpu:
        count: 1
        driverVersion: latest
        type: nvidia-h100-80gb
      machineType: a3-highgpu-1g
      maxPodsPerNode: 16
      reservations:
        affinity: AnyBestEffort
      spot: false

    # Use DWS FlexStart
    # - flexStart:
    #     enabled: true
    #     nodeRecycling:
    #       leadTimeSeconds: 3600
    #   gpu:
    #     count: 1
    #     driverVersion: latest
    #     type: nvidia-h100-80gb
    #   machineType: a3-highgpu-1g
    #   maxPodsPerNode: 16

    # Use spot
    - gpu:
        count: 1
        driverVersion: latest
        type: nvidia-h100-80gb
      machineType: a3-highgpu-1g
      maxPodsPerNode: 16
      spot: true

  nodePoolAutoCreation:
    enabled: true
