apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-h100-80gb-mega-x8
spec:
  activeMigration:
    optimizeRulePriority: true
  nodePoolAutoCreation:
    enabled: true
  priorities:
    # Use a specific reservation
    # - gpu:
    #     count: 8
    #     driverVersion: latest
    #     type: nvidia-h100-mega-80gb
    #   machineType: a3-megagpu-8g
    #   maxPodsPerNode: 32
    #   reservations:
    #     affinity: Specific
    #     specific:
    #       - name: nvidia-h100-mega-80gb-specific
    #         reservationBlock:
    #           name: <RESERVATION_NAME>
    #   spot: false

    # Use any reservation
    - gpu:
        count: 8
        driverVersion: latest
        type: nvidia-h100-mega-80gb
      machineType: a3-megagpu-8g
      maxPodsPerNode: 32
      reservations:
        affinity: AnyBestEffort
      spot: false

    # Use on-demand
    - gpu:
        count: 8
        driverVersion: latest
        type: nvidia-h100-mega-80gb
      machineType: a3-megagpu-8g
      maxPodsPerNode: 32
      spot: false

    # Use DWS FlexStart with 7 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      gpu:
        count: 8
        driverVersion: latest
        type: nvidia-h100-mega-80gb
      machineType: a3-megagpu-8g
      maxPodsPerNode: 32
      maxRunDurationSeconds: 604800

    # Use DWS FlexStart with 1 day limit
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      gpu:
        count: 8
        driverVersion: latest
        type: nvidia-h100-mega-80gb
      machineType: a3-megagpu-8g
      maxPodsPerNode: 32
      maxRunDurationSeconds: 86400

    # Use spot
    - gpu:
        count: 8
        driverVersion: latest
        type: nvidia-h100-mega-80gb
      machineType: a3-megagpu-8g
      maxPodsPerNode: 32
      spot: true
