# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: data-processing
        ml-platform: data-processing
    spec:
      containers:
        - name: job
          image: ${mft_data_processing_image_url}
          imagePullPolicy: Always
          env:
            - name: "DATASET_BUCKET"
              value: ${kaggle_bucket_name}
            - name: "DATASET_FILE_PATH"
              value: /datasets/PromptCloudHQ/flipkart-products/flipkart_com-ecommerce_sample.csv
            - name: "OUTPUT_BUCKET"
              value: ${mft_data_bucket_name}
            - name: "OUTPUT_CSV_FILE_PATH"
              value: /flipkart_preprocessed_dataset/flipkart.csv
            - name: "OUTPUT_IMAGE_FOLDER"
              value: flipkart_images
            - name: "RAY_CLUSTER_HOST"
              value: ray-cluster-kuberay-head-svc:10001
          resources:
            requests:
              cpu: 100m
              memory: 1.5Gi
            limits:
              cpu: 250m
              memory: 2Gi
      restartPolicy: Never
      serviceAccountName: ${mft_data_processing_service_account_name}
