# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-tracking
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: mlflow-tracking
    spec:
      containers:
        - args:
            - |
              mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlruns/mlflow.db
          command: ["sh", "-c"]
          image: ghcr.io/mlflow/mlflow:v2.15.1
          name: mlflow
          resources:
            limits:
              cpu: "2"
              memory: 10Gi
            requests:
              cpu: "2"
              memory: 10Gi
          volumeMounts:
            - mountPath: /mlruns
              name: gcs-fuse-csi-ephemeral
      serviceAccountName: ${service_account_name}
      tolerations:
        - effect: NoSchedule
          key: components.gke.io/gke-managed-components
          operator: Equal
          value: "true"
      volumes:
        - csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: ${bucket_name}
              gcsfuseLoggingSeverity: warning
              mountOptions: implicit-dirs
          name: gcs-fuse-csi-ephemeral
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-svc
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: mlflow-tracking
