steps:
  - id: 'Create Directories'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        dirs=(checkpoints clip clip_vision configs controlnet diffusers embeddings gligen hypernetworks loras style_models unet upscale_models vae vae_approx)
        for dir in "${dirs[@]}"; do
            mkdir -p /workspace/comfyui-models/$dir
            touch /workspace/comfyui-models/$dir/put_here
        done

  - id: 'Download SDXL Base Model'
    name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -L -o /workspace/comfyui-models/checkpoints/sd_xl_base_1.0.safetensors "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors?download=true"

  - id: 'Download SDXL Refiner Model'
    name: 'gcr.io/cloud-builders/curl' # Or any image with curl
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -L -o /workspace/comfyui-models/checkpoints/sd_xl_refiner_1.0.safetensors "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors?download=true"

  - id: 'Upload Models to GCS'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - "cp"
      - "-r"
      - "/workspace/comfyui-models/*"
      - "gs://${_BUCKET_NAME}/"

options:
  logging: CLOUD_LOGGING_ONLY