apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: kuberay-operator
    app.kubernetes.io/instance: kuberay-operator
    app.kubernetes.io/name: kuberay-operator
  name: kuberay-operator
