apiVersion: batch/v1
kind: Job
metadata:
  name: maxtext-rl-eval-job
  namespace: rl-kr-single-grpo-single-host
spec:
  backoffLimit: 0
  template:
    spec:
      tolerations:
      - operator: "Exists"
      containers:
      - args:
        - |
          set -ex

          CHAT_TEMPLATE_PATH=$(python3 -c "from maxtext.utils.globals import MAXTEXT_PKG_DIR; print(f'{MAXTEXT_PKG_DIR}/examples/chat_templates/gsm8k_rl.json')")

          echo "Starting MaxText 0.2.3 RL Checkpoint Evaluation on GSM8K..."

          python3 -m maxtext.trainers.post_train.rl.train_rl \
            model_name=${MODEL_NAME} \
            load_parameters_path=${LOAD_PARAMETERS_PATH} \
            run_name=${RUN_NAME} \
            base_output_directory=${BASE_OUTPUT_DIRECTORY} \
            hf_access_token=${HF_TOKEN} \
            chat_template_path=${CHAT_TEMPLATE_PATH} \
            tokenizer_path=${HF_MODEL_ID} \
            vllm_hf_config_path=${HF_MODEL_ID} \
            rl.loss_algo=grpo \
            use_pathways=False \
            debug.rl=False \
            rl.rollout_engine=vllm \
            rollout_tensor_parallelism=8 \
            rollout_data_parallelism=1 \
            rl.reasoning_start_token='<reasoning>' \
            rl.reasoning_end_token='</reasoning>' \
            rl.solution_start_token='<answer>' \
            rl.solution_end_token='</answer>' \
            batch_size=2 \
            rl.num_generations=8 \
            max_target_length=1024 \
            max_prefill_predict_length=256 \
            hbm_utilization_vllm=0.37 \
            num_batches=0 \
            reward_function_names="['gsm8k_accuracy']" \
            checkpoint_period=25 \
            num_test_batches=25 \
            eval_interval=100 \
            skip_jax_distributed_system=True \
            checkpoint_storage_use_zarr3=0 \
            checkpoint_storage_use_ocdbt=0 \
            managed_mldiagnostics=False \
            upload_all_profiler_results=False
        command:
        - /bin/bash
        - -c
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: hf-secret
        envFrom:
        - configMapRef:
            name: runtime-v6e-2x4-llama-3-1-8b-rl
        image: us-docker.pkg.dev/cloud-tpu-images/maxtext-images/tpu_post_training:0.2.3
        name: grpo-evaluator
        resources:
          limits:
            google.com/tpu: "8"
          requests:
            google.com/tpu: "8"
        volumeMounts:
        - mountPath: /root/.cache
          name: ephemeral-cache
        - mountPath: /tmp
          name: tmp-cache
      volumes:
      - name: ephemeral-cache
        emptyDir:
          sizeLimit: 150Gi
      - name: tmp-cache
        emptyDir:
          sizeLimit: 50Gi
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
        cloud.google.com/gke-tpu-topology: 2x4
        # Optional: Uncomment and set if targeting a specific Cloud TPU reservation
        # cloud.google.com/reservation-name: tpu-v6e-16c-batch-1-reservation
        topology.kubernetes.io/zone: us-east5-a
      restartPolicy: Never
      serviceAccountName: rl-kr-single-grpo-single-host-sa
