# https://black.readthedocs.io/en/stable/integrations/github_actions.html
name: Python formatter
on: 
- push
- pull_request
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: black --check
      uses: psf/black@stable
      with:
        options: "--check --diff --verbose"
        src: "./"
        version: "~= 22.0"