# https://black.readthedocs.io/en/stable/integrations/github_actions.html
name: Python lint
on: 
  - push
  - pull_request
jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./"
          version: "~= 22.0"
