name: Python checks
on: 
- push
- pull_request
jobs:
  # https://black.readthedocs.io/en/stable/integrations/github_actions.html
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: black --check
      uses: psf/black@stable
      with:
        options: "--check --diff --verbose"
        src: "./"
        version: "~= 22.0"
  # https://pycqa.github.io/isort/docs/configuration/github_action.html
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: isort --check-only --diff
        uses: isort/isort-action@v1
