name: Python Coverage Test

on:
  push:
    branches: [ gushob-preprocessing-script-changes ]
  pull_request:
    branches: [ gushob-preprocessing-script-changes ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt coverage
      - name: Run tests with coverage
        run: bash run_python_coverage_test.sh
      - name: Generate and print coverage report
        run: |
          cat .coveragerc
          coverage report --fail-under=0
  

      #cat coverage.xml
      # - name: Upload coverage report
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./coverage.xml